### PR TITLE
Fix outdated OpenSSL dependency

### LINKED ISSUE #12: OpenSSL dependency may need to be updated
The OpenSSL dependency installed in the library does not seem to work as expected. When the security library is installed in a project over 40+ errors are thrown while compiling. Either: 
1. The OpenSSL dependency is not being included in the static library build
2. The OpenSSL dependency is outdated
3. My working environment is not configured correctly

The only way I could fix the errors was by installing the OpenSSL-Universal library via Cocoapods (https://cocoapods.org/pods/OpenSSL-Universal ) to my project.

### PR DESCRIPTION
**Pull request by NicoleYarroch**
Fixes #12, #13  

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Smoke tests performed with sdl_core

### Summary
1. The new OpenSSL dependency was added to the root of the project in: **SDLSecurity > OpenSSL**
    * The **include** folder has the OpenSSL public headers
    * The **lib** folder has the  **libcrypto.a** and **libssl.a** static libraries
    * The **LICENSE** file contains the OpenSSL license from the build
 1. The included OpenSSL **libcrypto.a** and **libssl.a** static libraries are built for the `arm64` (iPhone 64-bit ARM processor) and `x86_64` (64-bit iPhone simulator) architectures. 
1. The *SDLSecurityStatic*'s custom run script was updated so it no longer throws an error about the wrong phone build.

#### If Adding a Different OpenSSL dependency
1. When dragging and dropping the **OpenSSL** folder into the project root, make sure to select the following in the popup:
    * Select **Copy items if needed**
    * In the **Add to Targets** section, select the *SDLSecurityStatic* target.
2. Configure the build settings for the targets.
    * For both the *SDLSecurity* and *SDLSecurityStatic* targets:
        * In **Build Settings > Library Search Paths** include the path to the **libcrypto.a** and **libssl.a** static libraries (`"$(SRCROOT)/Dependencies/OpenSSL/lib"`)
        * In **Build Settings > Header Search Paths** include the path to the **OpenSSL** public headers (`"$(SRCROOT)/Dependencies/OpenSSL/include"`)
    * For both the *SDLSecurityStatic* and *Resources* targets:
        * Set **Build Settings > Build Options > Enable Bitcode** to No. This must be done as the included **libcrypto.a** and **libssl.a** static libraries were not built to support bitcode (this feature can be added later). 
    * For the *SDLSecurityStatic* target:
        * To update the name of the folder where the generated public header files are placed edit the **Build Settings > Packaging > Public Headers Folder Path** (currently the folder's name is **include**)

#### Building the Library File and Adding It to an App
1. To build the *SDLSecurityStatic* target:
    * Run the the *SDLSecurityStatic* target (a simulator or device both work)
    * This generates three different builds of the *libSDLSecurityStatic.a* file, which can be found in the derived data of the project. 
        * *Debug-iphoneos* - will only work on an iPhone 
        * *Debug-iphonesimulator* - will only work on a simulator
        * *Debug-universal*  - will work on both the iPhone and simulator
    * In the **Products** folder select *libSDLSecurityStatic.a*, right click and select **Show in Finder**. This will take you to the three builds listed above.
2. To use the build in your project:
    *  Drag and drop 3 files into your project: **libSDLSecurityStatic.a**, **include/SDLSecurityConstants.h** and **include/SDLSecurityManager.h**. Make sure **libSDLSecurityStatic.a** has been added to your project's target membership.  
    *  To use the security manager, import **SDLSecurityManager.h** into where you are setting the encryption manager in your SDL project. If you have a Swift project, this will require adding a bridging-header to the project.
        * `let encryptionManager = SDLEncryptionConfiguration(securityManagers: [SDLSecurityManager.self]], delegate: nil)`

##### Enhancements
* Fixed the library not compiling in a project due to the outdated OpenSSL dependency.
* Fixed warning error thrown by the custom run script
### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by joeljfischer — CHANGES_REQUESTED** [review]
1. I'm seeing a few deprecation usages now that the library has been updated.
2. I'm not sure if it's just my setup but I'm seeing some weirdness in the scheme list. I have "SDLSecurity" (framework), "SDLSecurityStatic (SDLSecurity project)" (static), "SDLSecurityStaticRelease" (static), "SDLSecurityTestData" (unknown), "SDLSecurityStatic (SDLSecurity project)" (static, duplicate of above), "Resources" (resource build?). I don't think that all of these are probably supposed to be there?
3. Is the "Resources" target necessary?
4. When building a Swift app for the simulator, it built, but with ~560 warnings.
5. When building a Swift app for device, it failed with a warning: `'/Users/joel/Projects/Testing/SDL_Security_Test/TestSDLSecurity/libSDLSecurityStatic.a(SDLSecurityManager.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`

**Comment by NicoleYarroch** [comment]
> * I'm seeing a few deprecation usages now that the library has been updated.
> * I'm not sure if it's just my setup but I'm seeing some weirdness in the scheme list. I have "SDLSecurity" (framework), "SDLSecurityStatic (SDLSecurity project)" (static), "SDLSecurityStaticRelease" (static), "SDLSecurityTestData" (unknown), "SDLSecurityStatic (SDLSecurity project)" (static, duplicate of above), "Resources" (resource build?). I don't think that all of these are probably supposed to be there?
> * Is the "Resources" target necessary?
> * When building a Swift app for the simulator, it built, but with ~560 warnings.
> * When building a Swift app for device, it failed with a warning: `'/Users/joel/Projects/Testing/SDL_Security_Test/TestSDLSecurity/libSDLSecurityStatic.a(SDLSecurityManager.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`

1. Fixed. 
2. No idea what is happening here. I only the `SDLSecurityStatic` and `SDLSecurity` schemes in my project. 
3. Removed the **Resources** target
4. Fixed.
5. Fixed.

**Review by joeljfischer — CHANGES_REQUESTED** [review]
1. Attempting to build the dynamic framework version fails with numerous OpenSSL symbol errors
2. Attempting to import the universal binary into a test swift project causes the test project to fail to build with error:

```
'/Users/joel/Projects/Testing/SDL_Security_Test/TestSDLSecurity/libSDLSecurityStatic.a(SDLSecurityManager.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
```

Does bitcode need to be disabled for any project using the security library? If I disable bitcode for the application, building succeeds.

**Comment by NicoleYarroch** [comment]
> 1. Attempting to build the dynamic framework version fails with numerous OpenSSL symbol errors
> 2. Attempting to import the universal binary into a test swift project causes the test project to fail to build with error:
> 
> ```
> '/Users/joel/Projects/Testing/SDL_Security_Test/TestSDLSecurity/libSDLSecurityStatic.a(SDLSecurityManager.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
> ```
> 
> Does bitcode need to be disabled for any project using the security library? If I disable bitcode for the application, building succeeds.

1. Fixed. The dynamic framework version must be built on the platform that it is going to be used on (i.e. if it is going to be run on a simulator, then the scheme must be build on a simulator; same for a phone)
2. I double checked adding universal binary to a Swift project and building on both a phone and simulator with `ENABLE_BITCODE` set to `YES` on the Swift project. It worked fine for me. Did you delete your derived data and clean the build folder?

**Review by joeljfischer — APPROVED** [review]

**Pull request merged**
